# Generated by Django 6.0.2 on 2026-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('credit_amount', models.FloatField(verbose_name='Сумма кредита')),
                ('term_months', models.PositiveIntegerField(verbose_name='Срок в месяцах')),
            ],
            options={
                'verbose_name': 'Запись реестра',
                'verbose_name_plural': 'Реестр',
                'ordering': ['-id'],
            },
        ),
    ]
